[package]
name = "project_clank"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vosk = "0.2.0"
wav = "1.0.0"
cpal = "0.14.1"
